CREATE TABLE IF NOT EXISTS posts(
id INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
user_id INT (10) ,
title VARCHAR(255) NOT NULL,
content TEXT NOT NULL,
image TEXT NOT NULL,
FOREIGN KEY (user_id) REFERENCES user (id),
created_at DATETIME  NOT NULL
);