CREATE TABLE IF NOT EXISTS posts(
id INT(10) AUTO_INCREMENT PRIMARY KEY,
nickname VARCHAR(50) NOT NULL UNIQUE,
title VARCHAR(254) NOT NULL,
content TEXT NOT NULL,
image TEXT NOT NULL,
created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);